apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-login-deployment
  labels:
    app: my-springboot-login
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-springboot-login
  template:
    metadata:
      labels:
        app: my-springboot-login
    spec:
      containers:
      - name: my-springboot-login-container
        image: anonymousewashere/my-springboot-login:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "1024Mi"
          limits:
            cpu: "2000m"
            memory: "2048Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
        imagePullPolicy: Always
