apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-login-deployment
  labels:
    app: my-springboot-login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-springboot-login
  template:
    metadata:
      labels:
        app: my-springboot-login
    spec:
      containers:
      - name: my-springboot-login-container
        image: anonymousewashere/my-springboot-login:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "2048Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 40
          failureThreshold: 40
        imagePullPolicy: Always
